language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.init()'
  # manually add
  - julia -e 'Pkg.clone("https://github.com/r9y9/SPTK.jl.git"); Pkg.build("SPTK");'
  - julia -e 'Pkg.clone("https://github.com/r9y9/WORLD.jl.git"); Pkg.build("WORLD");'
  - julia -e 'Pkg.clone("https://github.com/r9y9/MCepAlpha.jl.git");'
  - julia -e 'Pkg.clone(pwd()); Pkg.test("VoiceConversion")'
