environment:
  matrix:
#  - JULIAVERSION: "win32"
  - JULIAVERSION: "win64"

skip_commits:
# Add [av skip] to commit messages for docfixes, etc to reduce load on queue
  message: /\[av skip\]/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile($("http://status.julialang.org/download/"+$env:JULIAVERSION), "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
  # Need to convert from shallow to complete for Pkg.clone to work
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo(); Pkg.init(); Pkg.clone(\"https://github.com/r9y9/MelGeneralizedCepstrums.jl\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/r9y9/SynthesisFilters.jl\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(pwd(), \"VoiceConversion\")"
test_script:
  - C:\projects\julia\bin\julia -e "Pkg.test(\"VoiceConversion\")"
